### PR TITLE
Support async functions

### LINKED ISSUE #20: async functions compatibility
It would be great if we could use log-derive with async functions. Adding `logfn` to an async function gives me the following:

```
error[E0728]: `await` is only allowed inside `async` functions and blocks
  --> src/models/video/mod.rs:94:9
   |
44 | #[logfn(ok = "INFO", err = "ERROR")]
   | ------------------------------------ this is not `async`
...
94 |         task::sleep(std::time::Duration::from_millis(500)).await;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ only allowed inside `async` functions and blocks
```

Source Snippet:
```
#[logfn(ok = "INFO", err = "ERROR")]
pub async fn create_video_sdp() {
// ...
```

### PR DESCRIPTION
**Pull request by silverjam**
Supports async functions by creating an async closure, then generating an async function wrapper.  This only works with nightly since async closures are not in stable (https://github.com/rust-lang/rust/issues/62290).  If this is a workable solution, then it fixes #20.

### CODE REVIEW

**Comment by DmitrySamoylov** [comment]
I tried to fix this too :smile: 

Looks like tests don't check what is actually printed. Try enabling SimpleLogger at the beginning of each test:
```rust
#[test]
fn works() {
    let _ = simplelog::SimpleLogger::init(simplelog::LevelFilter::Info, simplelog::Config::default());

    wrapped_function(5, "cool!");
    let a = AAAAAA;
    ...
}
```

and then run 
```
cargo test -- --nocapture --test-threads=1
```

and see difference between your version and initial.

I think it cannot be done as easy as replacing closure with a block because this case:
```rust
    #[logfn(Info)]
    fn third(&self, err: &Tes) -> Result<String, E> {
        if err.0 {
            return Err(E);
        } else {
            return Ok(String::from("Hi!"));
        }
    }
```
expanded to 
```rust

    fn third(&self, err: &Tes) -> Result<String, E> {
        let result: Result<String, E> = ({
            if err.0 {
                return Err(E);
            } else {
                return Ok(String::from("Hi!"));
            }
        });
        ....
```
This `return` statements bail you out from a function before printing anything.

**Comment by silverjam** [comment]
@DmitrySamoylov :man_facepalming: -- I did check things with `cargo expand` at one point, but this seems obvious now

**Comment by silverjam** [comment]
@DmitrySamoylov I think this gets closer, but it only works on nightly because it uses async closures: https://github.com/rust-lang/rust/issues/62290

**Comment by DmitrySamoylov** [comment]
Have a look at this: https://users.rust-lang.org/t/nested-async-block-fn/44560

The idea is to generate closure for usual functions and async block for `async fn`. Funny thing is that async blocks work like closures in regard of returns. Couldn't even think of that :smiley: 

And what's important is that this should work on stable.

**Comment by elichai** [comment]
Hi! Thanks for the contribution, this seem interesting.
I haven't looked into async closures / blocks enough to comment just yet, but if we can make this work on stable without any penalty that will be great :)

About the output, yeah the current tests require visually testing the output, but I should replace those with a `WriteLogger` and check the actual produced output, that way the CI could check that the output is correct.

**Comment by silverjam** [comment]
closed in favor of #22 or #24

**Pull request closed without merging**
