### PR TITLE
Add async support (with Travis)

### PR DESCRIPTION
**Pull request by silverjam**
Added Travis support to your PR (#22) @DmitrySamoylov

### CODE REVIEW

**Comment by DmitrySamoylov** [comment]
Yeah looks good! Thanks!

**Comment by silverjam** [comment]
@elichai How does this look?  I think we've resolved all concerns from the previous PR.

**Comment by elichai** [comment]
> @elichai How does this look? I think we've resolved all concerns from the previous PR.

Hi, Yeah it does look good, I'm currently swamped but this weekend I'll read about async blocks, test and merge this (and I hope I'll also make actual working tests that check that the log is correct)

**Comment by silverjam** [comment]
> > @elichai How does this look? I think we've resolved all concerns from the previous PR.
> 
> 
> 
> Hi, Yeah it does look good, I'm currently swamped but this weekend I'll read about async blocks, test and merge this (and I hope I'll also make actual working tests that check that the log is correct)

Sounds great! Thank you!

**Comment by DmitrySamoylov** [comment]
There were many changes in #22, so I used your changes for Travis there.

**Comment by silverjam** [comment]
closed in favor of #22

**Pull request closed without merging**
